id: a9f89211ca5049ec8effc509fa4ae63e
initial_creation_type: ocr
source_metadata:
  volumes:
    96f43e888f4f42e8a39b9575a83fbc3e:
      base_file: v036.txt
      image_group_id: I1PD95881
      title: ''
      total_pages: 1869
      volume_number: 36
